**Libraries**

In [1]:
import pybullet as p
import numpy as np
import time
import pybullet_data

pybullet build time: Mar 14 2024 13:49:57


**Setting up Pybullet Enviornment**

In [2]:
class Environment:
    
    def __init__(self):
        self.state = self.init_state()
        self.step_count = 0
        
    def init_state(self):
        p.connect(p.GUI)
        p.resetSimulation()
        p.setAdditionalSearchPath(pybullet_data.getDataPath())
        p.setGravity(0,0,-9.8)
        p.setRealTimeSimulation(0)  
        p.loadURDF("plane.urdf", [0,0,0], [0,0,0,1])
        self.pandaUID = p.loadURDF("franka_panda/panda.urdf", [0,0,0],[0,0,0,1],useFixedBase=True)
        finger_pos = p.getLinkState(self.pandaUID,9)[0]
        obs = np.array([finger_pos]).flatten()
        return obs
    
    def reset(self):
        p.disconnect()
        self.state = self.init_state()
        self.step_count = 0
    
    def step(self, action):
        
        self.step_count += 1
        p.setJointMotorControlArray(self.pandaUID, [4], p.POSITION_CONTROL, [action])
        p.stepSimulation()
        finger_pos = p.getLinkState(self.pandaUID,9)[0]
        
        if self.step_count >= 1000: # check for termination
            self.reset()
            finger_pos = p.getLinkState(self.pandaUID, 9)[0]
            obs = np.array([finger_pos]).flatten()
            self.state = obs
            reward = -1
            done = True
            return reward, done
        
        obs = np.array([finger_pos]).flatten()
        self.state = obs
        reward = -1
        done = False
        
        return reward, done

In [3]:
env = Environment()

for step in range(300):
    action = np.random.uniform(-2.0,2.0)
    reward, done = env.step(action)
    print(env.state)
    p.stepSimulation()

2024-05-17 10:23:54.916 Python[82609:8722008] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


[ 0.09507107 -0.00707107  0.8476    ]
[0.09531884 0.00182654 0.84759982]
[0.09497159 0.00832171 0.84759988]
[ 0.09277042 -0.01135837  0.84794324]
[ 0.09237485 -0.01489214  0.84792431]
[ 0.08442494 -0.03930663  0.84800424]
[ 0.08333847 -0.04225905  0.84794748]
[ 0.09336503 -0.00935332  0.84787614]
[ 0.09063522 -0.01543623  0.84821741]
[0.09270781 0.0106053  0.84797061]
[0.09096279 0.00236881 0.84838546]
[0.09056865 0.00902896 0.84838178]
[ 0.08614704 -0.01803127  0.8489034 ]
[ 0.08861607 -0.00857234  0.84872894]
[ 0.08099575 -0.03365819  0.84895511]
[ 0.07447055 -0.04748334  0.8488515 ]
[ 0.08125724 -0.03296366  0.84895913]
[ 0.08709813 -0.00280041  0.84905161]
[ 0.08246151 -0.01622618  0.84956582]
[ 0.0779297  -0.03200369  0.84953309]
[ 0.07494048 -0.03940044  0.84946444]
[ 0.08342331 -0.01105052  0.849548  ]
[0.08405453 0.00120426 0.84956186]
[ 0.0819916  -0.01188767  0.84975809]
[ 0.08145303 -0.01559912  0.84974488]
[0.08397056 0.01341707 0.84940285]
[0.08321764 0.0095949  0.84960987

error: Not connected to physics server.